project:
  type: website
  output-dir: docs

website:
  title: "Wil Rantala - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: lab0.qmd
        text: Home
      - text: Labs
        menu:
          - href: labs/lab_0/lab0.qmd
            text: "Lab 0: dplyr Basics"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto