project:
  type: website
  output-dir: docs

website:
  title: "Wil Rantala - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: labs/lab_0/index.qmd
            text: "Lab 0: dplyr Basics"
          - href: labs/lab_1/lab1.qmd
            text: "Lab 1: Census Data Exploration"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
